@extends('home.includes.master')
@section('content')
<div class="container">
    <div class="maroon">
        <h1>*** Cleaning Staffs ***</h1>
    </div>
    <div class="row">
        <div class="col-sm-8">
            <p>
                The <i><b>Cleaning Staff</b></i> in <b>Dewa Sharif</b> play a crucial role in maintaining the
                cleanliness and hygiene of the town, particularly around the Dargah of Hazrat Haji Waris Ali Shah, a
                site of great religious and cultural significance.
                Due to the large number of pilgrims and visitors who come to the Dargah throughout the year, especially
                during the annual Urs and other religious events, the demand for effective sanitation and cleanliness is
                high.

            <h4>Key Responsibilities:</h4>
            <i>
                <h5>Daily Cleaning of the Dargah Premises:
            </i></h5>
            The <i><b>Cleaning Staff</b></i> ensures that the main premises of the Dargah, including prayer halls,
            walkways, and courtyards, remain clean and free from litter. This is especially important as many visitors
            come to pay their respects, and maintaining a clean environment is a sign of respect and devotion.
            They are responsible for sweeping the floors, wiping surfaces, and managing waste disposal throughout the
            day to keep the sacred space tidy.

            <i>
                <h5>Waste Collection and Disposal:
            </i></h5>
            The staff collects waste from designated areas around the Dargah and the surrounding streets, including
            garbage bins placed for public use. Proper waste segregation and disposal are crucial to maintaining hygiene
            and preventing pollution.
            During large gatherings like the Urs, they work extra hours to manage the increased volume of waste
            generated by visitors and pilgrims.
            </p>
        </div>
        <div class="col-sm-4">
            <img src="{{asset('home/images/dewasharif/dewapage/cleaningstaff.jpg')}}" alt="">
        </div>
    </div>
    <div class="row">

        <p>
            <i>
                <h5>Support During Major Events:
            </i></h5>
            During events such as the Dewa Mela and the annual Urs of Hazrat Haji Waris Ali Shah, the influx of people
            increases significantly. The <i><b>Cleaning Staff</b></i> plays a key role in ensuring that temporary
            facilities like toilets and seating areas are clean and well-maintained.
            Their efforts help in managing the crowds more effectively and provide a cleaner, more welcoming environment
            for visitors.

            <i>
                <h5>Cleaning Public Spaces and Streets:
            </i></h5>
            Beyond the Dargah, the <i><b>Cleaning Staff</b></i> also maintains the cleanliness of streets, markets, and
            public areas in <b>Dewa Sharif</b> . Their work helps in keeping the town's overall environment clean and
            contributes to the well-being of the residents.
            They sweep streets, clear clogged drains, and ensure that public areas remain hygienic, which is
            particularly important during the rainy season when cleanliness can help prevent diseases.

        <h4>Importance:</h4>
        <i>
            <h5>Health and Hygiene:
        </i></h5>
        The cleaning staff’s efforts are crucial for preventing the spread of diseases and maintaining a healthy
        environment in <b>Dewa Sharif</b> . Clean surroundings are essential, especially in areas with high foot traffic
        like the Dargah.

        <i>
            <h5>Enhancing Pilgrim Experience:
        </i></h5>
        The cleanliness maintained by the staff ensures a positive experience for pilgrims and visitors who come to
        <b>Dewa Sharif</b> to seek spiritual solace. A clean and welcoming environment enhances the reputation of the
        town as a place of peace and spirituality.

        <i>
            <h5>Community Contribution:
        </i></h5>
        The work of the <i><b>Cleaning Staff</b></i> contributes to the well-being of the entire community, making them
        a vital part of Dewa Sharif’s daily life. Their efforts often go unrecognized, but they are foundational to
        maintaining the town’s cultural and spiritual sanctity.
        The <i><b>Cleaning Staff</b></i> of <b>Dewa Sharif</b> play a pivotal role in upholding the town's spiritual
        heritage by ensuring a clean and pleasant environment for both residents and visitors.
        Their dedication to maintaining the cleanliness of the Dargah and surrounding areas is essential for the town’s
        reputation and the comfort of those who come to <b>Dewa Sharif</b> for spiritual solace.

        </p>

    </div>

</div>

@endsection